/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/wrangler.jsonc --env=preview --include-runtime=false --strict-vars=false workers/worker-configuration.d.ts` (hash: 5458e0fc8c66b31307b1d8f31be028fc)
interface __BaseEnv_Env {
	DATA_BUCKET: R2Bucket;
	GOVERNANCE_DB: D1Database;
	ALLOWED_ORIGIN: string;
	SUPABASE_URL: string;
	GOVERNANCE_BOOTSTRAP_OWNER_SUB: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGIN" | "SUPABASE_URL" | "GOVERNANCE_BOOTSTRAP_OWNER_SUB">> {}
}
